[functions]
  external_node_modules = ["ejs", "express"]
  node_bundler = "esbuild"
  included_files = [
    "./views/**/*"
  ]
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/server/:splat"